---
- hosts: all # 指定伺服器部分: 所有伺服器
  remote_user: user # 遠端登入時的目前使用者
  become_user: user # 需要提權時的目前使用者
  become: true # 提高權限
  tasks:
    - name: "task1: Install Docker SDK for Python"
      ansible.builtin.pip:
        name: 
          - "docker==6.1.3"
          - "docker-compose"
    - name: "task2: Delete previous containers and images"
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - IoTGateway-cont
        - crawler-cont
        - TelegramB0t-cont
      ignore_errors: true
    - name: "task3: build a backend"
      community.docker.docker_compose:
        project_src: "/home/user/repo/2023_schoolResearch_Server-HW/src/Server"
        project_name: app_backend
        stopped: false
        build: true
        state: present
      register: output
      failed_when: output.failed



    
