- hosts: all # 指定伺服器部分: 所有伺服器
  remote_user: user # 遠端登入時的目前使用者
  become_user: user # 需要提權時的目前使用者
  become: true # 提高權限
  tasks:
    - name: "task1: check directory in fontend"
      file:
        path: /home/user/repo/2023_schoolResearch_ClientApp
        state: directory
      check_mode: no  # 設置為 yes 只進行檢查，而不進行任何更改
    - name: "task2: git fetch/pull fontend source code"
      git:
        repo: https://github.com/neko0xff/2023_schoolResearch_ClientApp
        dest: /home/user/repo/2023_schoolResearch_ClientApp
        version: main
        update: yes
        force: yes
    - name: "task3: check directory in backend"
      file:
        path: /home/user/repo/2023_schoolResearch_Server-HW
        state: directory
      check_mode: no  # 設置為 yes 只進行檢查，而不進行任何更改
    - name: "task4: git fetch/pull backend source code"
      git:
        repo: https://github.com/neko0xff/2023_schoolResearch_Server-HW
        dest: /home/user/repo/2023_schoolResearch_Server-HW
        version: main
        update: yes
        force: yes

